// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC98QEMmnVJPVXs5PR6azRNlMACLKw6XSE',
    appId: '1:432580227177:web:78e1f43a152b6eeb8db2f8',
    messagingSenderId: '432580227177',
    projectId: 'buildmate-app-c3e6f',
    authDomain: 'buildmate-app-c3e6f.firebaseapp.com',
    storageBucket: 'buildmate-app-c3e6f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD--RQwJOc096Wv7nfA5d8-Uki45_8GBO4',
    appId: '1:432580227177:android:17614773f20f1d9f8db2f8',
    messagingSenderId: '432580227177',
    projectId: 'buildmate-app-c3e6f',
    storageBucket: 'buildmate-app-c3e6f.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlzE7ZKFVd81KFk3G8xuDvvyRzNVL3aFg',
    appId: '1:432580227177:ios:91f90dd0fdf29e2d8db2f8',
    messagingSenderId: '432580227177',
    projectId: 'buildmate-app-c3e6f',
    storageBucket: 'buildmate-app-c3e6f.firebasestorage.app',
    iosClientId: '432580227177-ileihfjbsm23g3vfanhiks6u0ei8tvi0.apps.googleusercontent.com',
    iosBundleId: 'com.nexusbuild.nexusBuild',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlzE7ZKFVd81KFk3G8xuDvvyRzNVL3aFg',
    appId: '1:432580227177:ios:91f90dd0fdf29e2d8db2f8',
    messagingSenderId: '432580227177',
    projectId: 'buildmate-app-c3e6f',
    storageBucket: 'buildmate-app-c3e6f.firebasestorage.app',
    iosClientId: '432580227177-ileihfjbsm23g3vfanhiks6u0ei8tvi0.apps.googleusercontent.com',
    iosBundleId: 'com.nexusbuild.nexusBuild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC98QEMmnVJPVXs5PR6azRNlMACLKw6XSE',
    appId: '1:432580227177:web:58a5a93154df1f4f8db2f8',
    messagingSenderId: '432580227177',
    projectId: 'buildmate-app-c3e6f',
    authDomain: 'buildmate-app-c3e6f.firebaseapp.com',
    storageBucket: 'buildmate-app-c3e6f.firebasestorage.app',
  );
}
